### ISSUE TITLE
Repo name

### ISSUE THREAD

**Issue by kszh** [kszh/bowling-booking-system#1]
So, lets start! :-) 
Now we have empty project, but it is already has a problem.
Please, think about **appropriate** name for our project (repository).

**Comment by kszh** [comment]
Hey, what about "bowling-booking-system"?

**Comment by DrewNov** [comment]
cool :+1:

**Comment by DrewNov** [comment]
fasfa

**Comment by kszh** [comment]
Hey, what about "bowling-booking-system"?

**Comment by MarianaKotsko** [comment]
It's too long. It must be short and informative.

**Comment by MarianaKotsko** [comment]
What about "EasyBowlingBooking" ?

**Comment by kszh** [comment]
Hmm... No :exclamation:
